### ISSUE TITLE
Read notifications become unread when logging back in

### ISSUE THREAD

**Issue by hategan** [whole-tale/wt-design-docs#98] opened 2019-09-23 23:18 UTC
Steps to reproduce:
1. Do something that triggers notifications
2. Click on "Mark all as read"
3. Log out
4. Log back in

Notifications are displayed again. Can click "Mark all as read" and repeat from step 3.

**Comment by ThomasThelen** [comment] 2020-08-28 21:12
The notification system was recently refactored and I'm unable to reproduce this on the angular dashboard.

**Comment by Xarthisius** [comment] 2021-02-15 16:35
Fixed in the new dashboard.

**Closed by Xarthisius** 2021-02-15 16:35 UTC
