### ISSUE TITLE
File browser does not enforce name uniqueness

### ISSUE THREAD

**Issue by hategan** [whole-tale/wt-design-docs#101] opened 2019-09-27 05:04 UTC
Steps to reproduce:
1. Upload file to Home
2. Make a copy
3. Rename the copy to the original name

The file browser ~~and Girder~~ happily ~~go~~goes with it. ~~The problem is that we mount Home on a POSIX FS and, well, I'm not sure how that's supposed to work.~~

**Comment by Xarthisius** [comment] 2019-09-27 13:57
Girder doesn't allow objects of the same type with the same name on the same hierarchy level. My guess is that dashboard disregards the response. Check by refreshing the browser if the "renamed" file stays renamed.

**Comment by hategan** [comment] 2019-09-27 15:49
Indeed, upon refreshing, the old name is shown.

**Comment by ThomasThelen** [comment] 2020-08-28 21:14
Unable to reproduce on the angular dashboard. After renaming the file to the existing name, it immediately changes back to the previous name.

**Comment by bodom0015** [comment] 2022-09-27 21:08
A modal window now displays this error in the UI when it is encountered :+1:

> A folder or file with that name already exists here.

Closing this issue for now, but can reopen if additional work is needed

**Closed by bodom0015** 2022-09-27 21:08 UTC
Labels: area/ui-ux
