### ISSUE TITLE
Race condition in file browser resulting in wrong listing

### ISSUE THREAD

**Issue by hategan** [whole-tale/wt-design-docs#102] opened 2019-09-27 05:09 UTC
This may not be easy to reproduce, but is apparent with temporary or not so temporary network slowdowns. Steps:

1. Make sure there are files in "Home" and some registered data.
2. In "Manage" click on "Home"
3. Before the reply from the server comes back, click on "Data"

If timed right, the listing will include files from both "Home" and "Data".

**Comment by ThomasThelen** [comment] 2020-08-28 21:10
I was unable to reproduce this on the newer angular dashboard

**Comment by Xarthisius** [comment] 2021-02-15 16:35
Fixed in the new dashboard.

**Closed by Xarthisius** 2021-02-15 16:35 UTC
Labels: area/ui-ux
